---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: >
    static_resources:
      listeners:
      - name: listener_https
        address:
          socket_address: { address: 127.0.0.1, port_value: 8443 }
        traffic_direction: OUTBOUND
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              codec_type: auto
              stat_prefix: egress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: egress_db
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: egress_db
        connect_timeout: 2s
        type: strict_dns
        lb_policy: round_robin
        tls_context: 
          sni: grafana-envoy-test.lab.pathfinder.gov.bc.ca
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                  filename: "/etc/envoy/certs/client.crt"
                private_key:
                  filename: "/etc/envoy/certs/client.key"
            validation_context:
              trusted_ca:
                filename: "/etc/envoy/certs/ca.crt"
        load_assignment:
          cluster_name: egress_db
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: grafana-envoy-test.lab.pathfinder.gov.bc.ca
                    port_value: 443
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001